# Generated by Django 2.2 on 2019-04-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('company', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('start_date', models.CharField(max_length=100, unique=True)),
                ('end_date', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=2000, unique=True)),
            ],
        ),
    ]
