# Generated by Django 2.2 on 2019-04-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
