# Generated by Django 2.2 on 2019-04-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190410_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
    ]
