# Generated by Django 2.2 on 2019-04-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_job_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='deseight',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='desfive',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='desfour',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='desnine',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='desseven',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dessix',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='desten',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='desthree',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='destwo',
            field=models.CharField(default='SOME STRING', max_length=2000, unique=True),
        ),
    ]
