# Generated by Django 2.2 on 2019-04-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190410_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='deseight',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='desfive',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='desfour',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='desnine',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='desseven',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='dessix',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='desten',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='desthree',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='destwo',
            field=models.CharField(default='SOME STRING', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
