# Generated by Django 2.2 on 2019-04-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_experince'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experince',
            new_name='Skill',
        ),
    ]
